database:
  dialect: mysql
  dsn: root:123456@tcp(119.3.6.213:3306)/hks?charset=utf8mb4&parseTime=true
  debug: true

gin:
  mode: debug

session:
  size: 10
  network: tcp
  address: 119.3.6.213:6379
  password:
  keyPairs: 2019f854-9845-41b0-b583-bcc6e51fdbfb
