database:
  dialect: mysql
  dsn: root:"password"@tcp("ip":3306)/apigate-card?charset=utf8mb4&parseTime=true&loc=PRC
  debug: true

gin:
  mode: debug

session:
  size: 10
  network: tcp
  address: ip:6379
  password:
  keyPairs: 1914e743-9845-41b0-b583-bbb6e51fdaea
