database:
  dialect: mysql
  dsn: root:123456@tcp(127.0.0.1:3306)/hks?charset=utf8mb4&parseTime=true&loc=PRC
  debug: true

gin:
  mode: debug

session:
  size: 10
  network: tcp
  address: 127.0.0.1:6379
  password:
  keyPairs: 2015f854-9845-41b0-b583-bcc6e51fdbfb
