version: '3.1'
services:

  hks-core:
    image: registry.cn-chengdu.aliyuncs.com/wmicroservice/hks-core:b0.1
    volumes:
      - ./config.yaml:/var/config/config.yaml
      # - /etc/localtime:/etc/localtime
    ports:
      - "80:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=hks
    volumes:
      # - /etc/timezone:/etc/timezone
      # - /etc/localtime:/etc/localtime
      - /e/workspace/other/go/hks-core/build/mysqlData
    ports:
      - "3306:3306"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

  # nsqlookupd:
  #   image: nsqio/nsq
  #   command: /nsqlookupd
  #   ports:
  #    - "4160:4160"
  #    - "4161:4161"

  # nsqd:
  #   image: nsqio/nsq
  #   command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
  #   depends_on:
  #     - nsqlookupd
  #   ports:
  #    - "4150:4150"
  #    - "4151:4151"

  # nsqadmin:
  #   image: nsqio/nsq
  #   command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  #   depends_on:
  #    - nsqlookupd
  #   ports:
  #    - "4171:4171"
